version: '3'
services:
   mysql:
      container_name: mysql
      build: ./mysql
      command: mysqld_safe
   

   laravelnginx:
      container_name: laravelnginx
      build: ./laravel
      working_dir: /home/laravel
      ports:
      - 80:80
      depends_on:
      - mysql
      command: nginx -g 'daemon off;';


